export const data = {
  morrent: {
    title: "Morrent",
    titleDesc: "A Car Rental Website",
    lImage: "/job-image/Morrent-Laptop.svg",
    mImage: "/job-image/Morrent-Mobile.svg",
    demo: "https://cohort5-breaking-bugs-car-rent.vercel.app/",
    code: "https://github.com/JavaScript-Mastery-PRO/Cohort5_BreakingBugs_CarRent",
    myRole: "Software Engineer",
    start: "08/07/2023",
    end: "09/03/2023",
    techStack: [
      "/color-icon/react.svg",
      "/color-icon/redux.svg",
      "/color-icon/next.svg",
      "/color-icon/ts.svg",
      "/color-icon/html.svg",
      "/color-icon/css.svg",
      "/color-icon/sass.svg",
      "/color-icon/tailwind.svg",
      "/color-icon/motion.svg",
      "/color-icon/git.svg",
      "/color-icon/github.svg",
      "/color-icon/nodejs.svg",
      "/color-icon/mongodb.svg",
    ],
    desc: [
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a dynamic homepage that showcases featured vehicles, along with convenient pickup & drop-off location options & a comprehensive list of available cars.",
      "My team and I also developed the car listing page which offers a search bar and various filtering options for users to find the perfect vehicle. Additionally, it has a car details page which provides users with detailed information along with suggestions for other recommended vehicles.",
      "Car owners are also able to list their cars for rent through our Add Car page, while users can easily track their rented and rented-out cars through their profile page. Overall, we have created an intuitive and user-friendly MVP version of the platform that will make renting a car a breeze.",
    ],
    problem:
      "One of the main problems that people face when looking to rent a car is the hassle of finding a reliable and user-friendly platform to search for and book rental cars. In addition, car owners who want to rent out their vehicles often struggle to find a suitable platform to list their cars and manage their rentals.",
    image: "/job-image/Morrent-ex.svg",
    figma: "/job-image/Morrent-Figma.svg",
    challenge: [
      "Gained extensive knowledge of full authentication and authorization implementation, including the use of industry-standard security protocols such as JSON Web Tokens.",
      "We conducted brainstorming and carefully weighed our options before making a decision. Furthermore, using NextJS was a new experience for us, and we encountered difficulties while implementing its features. Finally, we had to work under time constraints, which added pressure to the project. ",
      "However, we collaborated effectively to overcome these obstacles and ultimately delivered a high-quality product within the given timeline.",
    ],
    learning: [
      "Gained extensive knowledge of full authentication and authorization implementation, including the use of industry-standard security protocols such as JSON Web Tokens.",
      "Sharpened my backend skills, specifically in optimizing database queries, improving performance, and handling server-side logic.",
      "Learned how to properly handle files, including file upload, storage, and retrieval, ensuring that the app's data is organized & easily accessible while keeping it secure.",
      "Acquired proficiency in NextJS and implemented various features utilizing industry-standard best practices.",
    ],
    image1: "/job-image/JobIt-Figma.svg",
    title1: "JobIT",
    desc1:
      "Jobit, a web app made with React and JSearch API, links developers to millions of job openings. It offers easy job search by...",
    link1: "/casestudies/jobit",
    image2: "/job-image/Hipnode-Figma.svg",
    title2: "HipNode",
    desc2:
      "Jobit, a web app made with React and JSearch API, links developers to millions of job openings. It offers easy job search by...",
    link2: "/casestudies/jobit",
  },

  jobit: {
    title: "JobIT",
    titleDesc: "A Jobs Finding Website",
    lImage: "/job-image/JobIT-Laptop.svg",
    mImage: "/job-image/JobIT-Mobile.svg",
    demo: "https://cohort5-breaking-bugs-car-rent.vercel.app/",
    code: "https://github.com/JavaScript-Mastery-PRO/Cohort5_BreakingBugs_CarRent",
    myRole: "Software Engineer",
    start: "07/10/2023",
    end: "08/06/2023",
    techStack: [
      "/color-icon/react.svg",
      "/color-icon/redux.svg",
      "/color-icon/next.svg",
      "/color-icon/ts.svg",
      "/color-icon/html.svg",
      "/color-icon/css.svg",
      "/color-icon/sass.svg",
      "/color-icon/tailwind.svg",
      "/color-icon/motion.svg",
      "/color-icon/git.svg",
      "/color-icon/github.svg",
      "/color-icon/nodejs.svg",
      "/color-icon/mongodb.svg",
    ],
    desc: [
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a dynamic homepage that showcases featured vehicles, along with convenient pickup & drop-off location options & a comprehensive list of available cars.",
      "My team and I also developed the car listing page which offers a search bar and various filtering options for users to find the perfect vehicle. Additionally, it has a car details page which provides users with detailed information along with suggestions for other recommended vehicles.",
      "Car owners are also able to list their cars for rent through our Add Car page, while users can easily track their rented and rented-out cars through their profile page. Overall, we have created an intuitive and user-friendly MVP version of the platform that will make renting a car a breeze.",
    ],
    problem:
      "One of the main problems that people face when looking to rent a car is the hassle of finding a reliable and user-friendly platform to search for and book rental cars. In addition, car owners who want to rent out their vehicles often struggle to find a suitable platform to list their cars and manage their rentals.",
    image: "/job-image/Morrent-ex.svg",
    figma: "/job-image/JobIt-Figma.svg",
    challenge: [
      "Gained extensive knowledge of full authentication and authorization implementation, including the use of industry-standard security protocols such as JSON Web Tokens.",
      "We conducted brainstorming and carefully weighed our options before making a decision. Furthermore, using NextJS was a new experience for us, and we encountered difficulties while implementing its features. Finally, we had to work under time constraints, which added pressure to the project. ",
      "However, we collaborated effectively to overcome these obstacles and ultimately delivered a high-quality product within the given timeline.",
    ],
    learning: [
      "Gained extensive knowledge of full authentication and authorization implementation, including the use of industry-standard security protocols such as JSON Web Tokens.",
      "Sharpened my backend skills, specifically in optimizing database queries, improving performance, and handling server-side logic.",
      "Learned how to properly handle files, including file upload, storage, and retrieval, ensuring that the app's data is organized & easily accessible while keeping it secure.",
      "Acquired proficiency in NextJS and implemented various features utilizing industry-standard best practices.",
    ],
    image1: "/job-image/Morrent-Figma.svg",
    title1: "Morrent",
    desc1:
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a...",
    link1: "/casestudies/jobitv2",
    image2: "/job-image/Hipnode-Figma.svg",
    title2: "HipNode",
    desc2:
      "Jobit, a web app made with React and JSearch API, links developers to millions of job openings. It offers easy job search by...",
    link2: "/casestudies/jobit",
  },
};
