export const data = {
  morrent: {
    title: "Morrent",
    titleDesc: "A Car Rental Website",
    lImage: "/job-image/Morrent-Laptop.svg",
    mImage: "/job-image/Morrent-Mobile.svg",
    demo: "https://cohort5-breaking-bugs-car-rent.vercel.app/",
    code: "https://github.com/JavaScript-Mastery-PRO/Cohort5_BreakingBugs_CarRent",
    myRole: "Software Engineer",
    start: "08/07/2023",
    end: "09/03/2023",
    techStack: [
      "/color-icon/react.svg",
      "/color-icon/redux.svg",
      "/color-icon/next.svg",
      "/color-icon/ts.svg",
      "/color-icon/html.svg",
      "/color-icon/css.svg",
      "/color-icon/sass.svg",
      "/color-icon/tailwind.svg",
      "/color-icon/motion.svg",
      "/color-icon/git.svg",
      "/color-icon/github.svg",
      "/color-icon/nodejs.svg",
      "/color-icon/mongodb.svg",
    ],
    desc: [
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a dynamic homepage that showcases featured vehicles, along with convenient pickup & drop-off location options & a comprehensive list of available cars.",
      "My team and I also developed the car listing page which offers a search bar and various filtering options for users to find the perfect vehicle. Additionally, it has a car details page which provides users with detailed information along with suggestions for other recommended vehicles.",
      "Car owners are also able to list their cars for rent through our Add Car page, while users can easily track their rented and rented-out cars through their profile page. Overall, we have created an intuitive and user-friendly MVP version of the platform that will make renting a car a breeze.",
    ],
    problem:
      "One of the main problems that people face when looking to rent a car is the hassle of finding a reliable and user-friendly platform to search for and book rental cars. In addition, car owners who want to rent out their vehicles often struggle to find a suitable platform to list their cars and manage their rentals.",
    image: "/job-image/Morrent-ex.svg",
    figma: "/job-image/Morrent-Figma.svg",

    challenge: [
      "We conducted brainstorming and carefully weighed our options before making a decision. Furthermore, using NextJS was a new experience for us, and we encountered difficulties while implementing its features. Finally, we had to work under time constraints, which added pressure to the project. ",
      "However, we collaborated effectively to overcome these obstacles and ultimately delivered a high-quality product within the given timeline.",
    ],
    learning: [
      "Gained extensive knowledge of full authentication and authorization implementation, including the use of industry-standard security protocols such as JSON Web Tokens.",
      "Sharpened my backend skills, specifically in optimizing database queries, improving performance, and handling server-side logic.",
      "Learned how to properly handle files, including file upload, storage, and retrieval, ensuring that the app's data is organized & easily accessible while keeping it secure.",
      "Acquired proficiency in NextJS and implemented various features utilizing industry-standard best practices.",
    ],
    image1: "/job-image/MindLikes-Laptop.png",
    title1: "MindLikes",
    desc1:
      "MindLikes, a platform where developers can interact with other developers to ask and answer questions...",
    link1: "/casestudies/mindlikes",
    image2: "/job-image/Hipnode-Figma.svg",
    title2: "HipNode",
    desc2:
      "Jobit, a web app made with React and JSearch API, links developers to millions of job openings. It offers easy job search by...",
    link2: "/casestudies/hipnode",
  },

  jobit: {
    title: "JobIT",
    titleDesc: "A Jobs Finding Website",
    lImage: "/job-image/JobIT-Laptop.svg",
    mImage: "/job-image/JobIT-Mobile.svg",
    demo: "https://cohort5-next-hooligans-job-it.vercel.app/",
    code: "https://github.com/JavaScript-Mastery-PRO/Cohort5_NextHooligans_JobIt",
    myRole: "Software Engineer",
    start: "07/10/2023",
    end: "08/06/2023",
    techStack: [
      "/color-icon/react.svg",
      "/color-icon/redux.svg",
      "/color-icon/next.svg",
      "/color-icon/ts.svg",
      "/color-icon/html.svg",
      "/color-icon/css.svg",
      "/color-icon/sass.svg",
      "/color-icon/tailwind.svg",
      "/color-icon/motion.svg",
      "/color-icon/git.svg",
      "/color-icon/github.svg",
      "/color-icon/nodejs.svg",
      "/color-icon/mongodb.svg",
    ],
    desc: [
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a dynamic homepage that showcases featured vehicles, along with convenient pickup & drop-off location options & a comprehensive list of available cars.",
      "My team and I also developed the car listing page which offers a search bar and various filtering options for users to find the perfect vehicle. Additionally, it has a car details page which provides users with detailed information along with suggestions for other recommended vehicles.",
      "Car owners are also able to list their cars for rent through our Add Car page, while users can easily track their rented and rented-out cars through their profile page. Overall, we have created an intuitive and user-friendly MVP version of the platform that will make renting a car a breeze.",
    ],
    problem:
      "One of the main problems that people face when looking to rent a car is the hassle of finding a reliable and user-friendly platform to search for and book rental cars. In addition, car owners who want to rent out their vehicles often struggle to find a suitable platform to list their cars and manage their rentals.",
    image: "/job-image/Morrent-ex.svg",
    figma: "/job-image/JobIt-Figma.svg",
    challenge: [
      "Gained extensive knowledge of full authentication and authorization implementation, including the use of industry-standard security protocols such as JSON Web Tokens.",
      "We conducted brainstorming and carefully weighed our options before making a decision. Furthermore, using NextJS was a new experience for us, and we encountered difficulties while implementing its features. Finally, we had to work under time constraints, which added pressure to the project. ",
      "However, we collaborated effectively to overcome these obstacles and ultimately delivered a high-quality product within the given timeline.",
    ],
    learning: [
      "Gained extensive knowledge of full authentication and authorization implementation, including the use of industry-standard security protocols such as JSON Web Tokens.",
      "Sharpened my backend skills, specifically in optimizing database queries, improving performance, and handling server-side logic.",
      "Learned how to properly handle files, including file upload, storage, and retrieval, ensuring that the app's data is organized & easily accessible while keeping it secure.",
      "Acquired proficiency in NextJS and implemented various features utilizing industry-standard best practices.",
    ],
    image1: "/job-image/Morrent-Figma.svg",
    title1: "Morrent",
    desc1:
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a...",
    link1: "/casestudies/morrent",
    image2: "/job-image/Hipnode-Figma.svg",
    title2: "HipNode",
    desc2:
      "HipNode, a social media platform where users can make posts, upload podcasts, create meetups and groups, and...",
    link2: "/casestudies/hipnode",
  },

  mindlikes: {
    title: "MindLikes",
    titleDesc: "A Developer Forum",
    lImage: "/job-image/MindLikes-Laptop.png",
    mImage: "/job-image/MindLikes-Mobile.png",
    demo: "https://mind-likes-lushi-lius-projects.vercel.app/",
    code: "https://github.com/lushi-liu/mind-likes",
    myRole: "Software Engineer",
    start: "09/03/2023",
    end: "12/05/2023",
    techStack: [
      "/color-icon/react.svg",
      "/color-icon/redux.svg",
      "/color-icon/next.svg",
      "/color-icon/ts.svg",
      "/color-icon/html.svg",
      "/color-icon/css.svg",
      "/color-icon/sass.svg",
      "/color-icon/tailwind.svg",
      "/color-icon/motion.svg",
      "/color-icon/git.svg",
      "/color-icon/github.svg",
      "/color-icon/nodejs.svg",
      "/color-icon/mongodb.svg",
    ],
    desc: [
      "MindLikes, a platform where developers can interact with other developers to ask and answer questions. It utilized the MERN stack to its fullest extend, with users ebing able to save questions, comment on them, join communities, filter by tags, and much more.",
      "The platform has a intuitive global and local search and filter system which users can fully take advantage of to efficiently search for questions, users, communities, etc. Each user has a contribution and medal system which users can gain by interacting with posts.",
      "Users can upvote, downvote and save questions they choose to and view them in their profilem as well as view the top questions and popular tags. The platform also utilizes OpenAI API that allows users to answer questions using AI generated answers.",
    ],
    problem:
      "Developers often grapple with the challenge of finding a dedicated platform where they can engage with like-minded individuals, seek expert advice, and share their expertise. Existing platforms may lack the necessary features or community engagement tools, leading to fragmented experiences. Moreover, with the evolving landscape of technology and development, there is a growing need for a platform that integrates advanced functionalities, such as AI-generated responses, to address users' queries comprehensively and efficiently.",
    image: "/job-image/MindLikes-ex.jpg",
    figma: "none",
    challenge: [
      "Undertaking MindLikes as a solo project brought forth a myriad of challenges. From conceptualizing the platform's core functionalities to integrating advanced features like the OpenAI API, every step required thorough planning and execution. The responsibility of making critical decisions solely rested on me, demanding a deep understanding of both frontend and backend intricacies.",
      "Developing an intuitive search and filtering mechanism that aligns with the needs of the developer community was particularly challenging. Furthermore, ensuring that the platform could scale efficiently while maintaining optimal performance added complexity to the development process.",
      "Despite these hurdles, I persevered by adopting a structured approach, prioritizing tasks, and leveraging resources effectively. This solo endeavor not only honed my technical skills but also instilled a sense of discipline and resilience in managing comprehensive projects from start to finish.",
    ],
    learning: [
      "Deepened my expertise in crafting end-to-end solutions, encompassing frontend design, backend development, and database management, to create a cohesive platform tailored for developers.",
      "Mastered the integration of third-party APIs, exemplified by the seamless incorporation of the OpenAI API to enhance user interactions and provide AI-generated insights.",
      "Acquired hands-on experience in designing and implementing user-centric features, such as the contribution and medal system, to foster community engagement and recognize user contributions.",
      "Developed a comprehensive skill set in optimizing platform performance, ensuring efficient data retrieval, storage, and overall user experience.",
    ],
    image1: "/job-image/Morrent-Figma.svg",
    title1: "Morrent",
    desc1:
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a...",
    link1: "/casestudies/morrent",
    image2: "/job-image/Hipnode-Figma.svg",
    title2: "HipNode",
    desc2:
      "HipNode, a social media platform where users can make posts, upload podcasts, create meetups and groups, and...",
    link2: "/casestudies/hipnode",
  },

  hipnode: {
    title: "HipNode",
    titleDesc: "A Social Media Platform",
    lImage: "/job-image/HipNode-Laptop.png",
    mImage: "/job-image/HipNode-Mobile.png",
    demo: "https://mind-likes-lushi-lius-projects.vercel.app/",
    code: "https://github.com/lushi-liu/mind-likes",
    myRole: "Software Engineer",
    start: "10/02/2023",
    end: "1/30/2023",
    techStack: [
      "/color-icon/react.svg",
      "/color-icon/redux.svg",
      "/color-icon/next.svg",
      "/color-icon/ts.svg",
      "/color-icon/html.svg",
      "/color-icon/css.svg",
      "/color-icon/sass.svg",
      "/color-icon/tailwind.svg",
      "/color-icon/motion.svg",
      "/color-icon/git.svg",
      "/color-icon/github.svg",
      "/color-icon/nodejs.svg",
      "/color-icon/mongodb.svg",
    ],
    desc: [
      "HipNode, a social media platform where users can make posts, upload podcasts, create meetups and groups, and post interview opportunities. Users can like and save posts, comment on them, and share it on other platforms such as LinkedIn",
      "Users can interact with other users through a messaging and notification system that utilizes sockets for live updates. The platform uses NextAuth to handle user infos and login. It uses a MERN stack to store user and website information and allow users to interact with it seamlessly.",
      "The platform utilizes Cloudinary to allow users to upload images and audio files. When listening to podcasts, users can maneuver to other pages while still listening.",
    ],
    problem:
      "Despite the plethora of social media platforms available, there remains a gap in the market for a comprehensive platform that seamlessly integrates various content types like posts, podcasts, meetups, and interview opportunities. Many existing platforms either focus on one specific content type or lack the cohesive integration of multiple features, leading to fragmented user experiences. Additionally, the need for real-time interactions and notifications remains unmet in many platforms, hindering immediate engagement and fostering a sense of community. Moreover, existing platforms often face challenges in providing seamless user authentication and media storage solutions, making it cumbersome for users to navigate and interact effectively. As the digital landscape evolves, there is a growing demand for a unified social media platform that addresses these gaps, offering users a holistic and engaging experience.",
    image: "/job-image/Hipnode-ex.jpg",
    figma: "/job-image/Hipnode-Figma.svg",
    challenge: [
      "Designing and implementing a multifaceted social media platform like HipNode posed numerous challenges. Integrating diverse features such as posts, podcasts, meetups, and interview opportunities required meticulous planning to ensure a seamless user experience.",
      "Implementing real-time messaging and notification systems using sockets demanded a deep understanding of real-time communication protocols and efficient data synchronization techniques.",
      "Managing user authentication and security was another significant challenge, especially while integrating NextAuth to handle user information securely and efficiently.",
      "Incorporating Cloudinary for media uploads and ensuring smooth playback of podcasts while allowing users to navigate across pages posed technical challenges related to media storage, retrieval, and seamless user interaction.",
    ],
    learning: [
      "Enhanced my proficiency in building comprehensive social media platforms by gaining hands-on experience in integrating diverse features and functionalities tailored to user needs.",
      "Expanded my knowledge of real-time communication protocols and socket-based systems, acquiring essential skills in creating interactive and engaging user experiences.",
      "Deepened my understanding of user authentication and security measures, mastering the integration of NextAuth to ensure robust user data protection and seamless login experiences.",
      "Acquired valuable insights into media management and playback optimization, learning how to efficiently handle and store user-uploaded content while ensuring uninterrupted playback across various platform functionalities.",
    ],
    image1: "/job-image/Morrent-Figma.svg",
    title1: "Morrent",
    desc1:
      "Morent, a cutting-edge car rental application that was developed using the MERN stack. The app boasts a...",
    link1: "/casestudies/morrent",
    image2: "/job-image/MindLikes-Laptop.png",
    title2: "MindLikes",
    desc2:
      "MindLikes, a platform where developers can interact with other developers to ask and answer questions...",
    link2: "/casestudies/mindlikes",
  },
};
